  # rpmrebuild autogenerated specfile

%define defaultbuildroot /
AutoProv: no
%undefine __find_provides
AutoReq: no
%undefine __find_requires
# Do not try autogenerate prereq/conflicts/obsoletes and check files
%undefine __check_files
%undefine __find_prereq
%undefine __find_conflicts
%undefine __find_obsoletes
# Be sure buildpolicy set to do nothing
%define __spec_install_post %{nil}
# Something that need for rpm-4.1
%define _missing_doc_files_terminate_build 0
#dummy
#dummy
#BUILDHOST:    centos7.cbg.collabora.co.uk
#BUILDTIME:    Mon Jun 19 13:20:47 2017
#SOURCERPM:    loolwsd-2.1.2-6.el7.centos.src.rpm

#RPMVERSION:   4.11.3
#COOKIE:       centos7.cbg.collabora.co.uk 1497878447
#INSTALLTIME:  Fri Jul  7 09:10:21 2017

#OS:           linux
#SIZE:           12009025
#ARCHIVESIZE:           12119344
#ARCH:         x86_64
BuildArch:     x86_64
Name:          loolwsd
Version:       2.1.3
Release:       6.el7.centos
License:       MPL
Group:         Unspecified
Summary:       LibreOffice On-Line WebSocket Daemon
Source1:        static.tar.gz
Source2:        ui-bg_highlight-soft_100_eeeeee_1x100.png
#Source1:       etc/cron.d/loolwsd.cron
#Source2:       etc/loolwsd/loolwsd.xml
#Source3:       etc/loolwsd/loolkitconfig.xcu
#Source4:       usr/share/doc/loolwsd/protocol.txt
#Source5:       usr/share/doc/loolwsd/README
#Source6:       usr/share/doc/loolwsd/README.vars
#Source7:       usr/share/doc/loolwsd/reference.txt
#Source8:       usr/share/doc/loolwsd-2.1.2/README
#Source9:       ui-bg_highlight-soft_100_eeeeee_1x100.png
Vendor:        Collabora
Obsoletes:     loleaflet <= 1.5.8
Provides:      config(loolwsd) = 2.1.3-4.el7.centos
Provides:      loleaflet = 1.5.8
Provides:      loolwsd = 2.1.3-4.el7.centos
Provides:      loolwsd(x86-64) = 2.1.2-4.el7.centos
Requires:      /bin/bash
Requires:      /bin/sh
Requires:      /bin/sh
Requires:      /bin/sh
Requires:      /bin/sh
Requires:      GConf2
Requires:      atk
Requires:      avahi-glib
Requires:      avahi-libs
Requires:      bzip2-libs
Requires:      cairo
Requires:      collaboraoffice5.3 >= 5.3.10.15
Requires:      collaboraoffice5.3-ure >= 5.3.10.15
Requires:      collaboraofficebasis5.3-calc >= 5.3.10.15
Requires:      collaboraofficebasis5.3-core >= 5.3.10.15
Requires:      collaboraofficebasis5.3-draw >= 5.3.10.15
Requires:      collaboraofficebasis5.3-en-US >= 5.3.10.15
Requires:      collaboraofficebasis5.3-en-US-calc >= 5.3.10.15
Requires:      collaboraofficebasis5.3-en-US-res >= 5.3.10.15
Requires:      collaboraofficebasis5.3-extension-pdf-import >= 5.3.10.15
Requires:      collaboraofficebasis5.3-graphicfilter >= 5.3.10.15
Requires:      collaboraofficebasis5.3-images >= 5.3.10.15
Requires:      collaboraofficebasis5.3-impress >= 5.3.10.15
Requires:      collaboraofficebasis5.3-noto-fonts >= 5.3.10.15
Requires:      collaboraofficebasis5.3-ooofonts >= 5.3.10.15
Requires:      collaboraofficebasis5.3-writer >= 5.3.10.15
Requires:      config(loolwsd) = 2.1.3-4.el7.centos
Requires:      coreutils
Requires:      cups-libs
Requires:      dbus-glib
Requires:      dbus-libs
Requires:      expat
Requires:      fontconfig
Requires:      freetype
Requires:      gdk-pixbuf2
Requires:      glib2
Requires:      gnome-vfs2
Requires:      graphite2
Requires:      grep
Requires:      gstreamer
Requires:      gstreamer-plugins-base
Requires:      gtk2
Requires:      harfbuzz
Requires:      keyutils-libs
Requires:      krb5-libs
Requires:      libICE
Requires:      libPocoCrypto.so.45()(64bit)
Requires:      libPocoFoundation.so.45()(64bit)
Requires:      libPocoJSON.so.45()(64bit)
Requires:      libPocoNet.so.45()(64bit)
Requires:      libPocoNetSSL.so.45()(64bit)
Requires:      libPocoUtil.so.45()(64bit)
Requires:      libPocoXML.so.45()(64bit)
Requires:      libSM
Requires:      libX11
Requires:      libXau
Requires:      libXcomposite
Requires:      libXcursor
Requires:      libXdamage
Requires:      libXext
Requires:      libXfixes
Requires:      libXi
Requires:      libXinerama
Requires:      libXrandr
Requires:      libXrender
Requires:      libXt
Requires:      libXxf86vm
Requires:      libattr
Requires:      libc.so.6()(64bit)
Requires:      libc.so.6(GLIBC_2.10)(64bit)
Requires:      libc.so.6(GLIBC_2.11)(64bit)
Requires:      libc.so.6(GLIBC_2.14)(64bit)
Requires:      libc.so.6(GLIBC_2.2.5)(64bit)
Requires:      libc.so.6(GLIBC_2.3)(64bit)
Requires:      libc.so.6(GLIBC_2.3.3)(64bit)
Requires:      libc.so.6(GLIBC_2.3.4)(64bit)
Requires:      libc.so.6(GLIBC_2.4)(64bit)
Requires:      libc.so.6(GLIBC_2.9)(64bit)
Requires:      libcap
Requires:      libcap.so.2()(64bit)
Requires:      libcom_err
Requires:      libcrypto.so.10()(64bit)
Requires:      libcrypto.so.10(OPENSSL_1.0.1_EC)(64bit)
Requires:      libcrypto.so.10(libcrypto.so.10)(64bit)
Requires:      libdl.so.2()(64bit)
Requires:      libdl.so.2(GLIBC_2.2.5)(64bit)
Requires:      libdrm
Requires:      libffi
Requires:      libgcc
Requires:      libgcc_s.so.1()(64bit)
Requires:      libgcc_s.so.1(GCC_3.0)(64bit)
Requires:      libm.so.6()(64bit)
Requires:      libpcre.so.1()(64bit)
Requires:      libpng
Requires:      libpng15.so.15()(64bit)
Requires:      libpng15.so.15(PNG15_0)(64bit)
Requires:      libpthread.so.0()(64bit)
Requires:      libpthread.so.0(GLIBC_2.2.5)(64bit)
Requires:      libpthread.so.0(GLIBC_2.3.2)(64bit)
Requires:      libselinux
Requires:      libssl.so.10()(64bit)
Requires:      libssl.so.10(libssl.so.10)(64bit)
Requires:      libstdc++.so.6()(64bit)
Requires:      libstdc++.so.6(CXXABI_1.3)(64bit)
Requires:      libstdc++.so.6(CXXABI_1.3.5)(64bit)
Requires:      libstdc++.so.6(GLIBCXX_3.4)(64bit)
Requires:      libstdc++.so.6(GLIBCXX_3.4.11)(64bit)
Requires:      libstdc++.so.6(GLIBCXX_3.4.13)(64bit)
Requires:      libstdc++.so.6(GLIBCXX_3.4.14)(64bit)
Requires:      libstdc++.so.6(GLIBCXX_3.4.15)(64bit)
Requires:      libstdc++.so.6(GLIBCXX_3.4.18)(64bit)
Requires:      libstdc++.so.6(GLIBCXX_3.4.19)(64bit)
Requires:      libstdc++.so.6(GLIBCXX_3.4.9)(64bit)
Requires:      libuuid
Requires:      libxcb
Requires:      libxshmfence
Requires:      libz.so.1()(64bit)
Requires:      mesa-libEGL
Requires:      mesa-libGL
Requires:      mesa-libgbm
Requires:      mesa-libglapi
Requires:      openssl-libs
Requires:      pango
Requires:      pcre
Requires:      pixman
Requires:      poco-crypto >= 1.7.5
Requires:      poco-foundation >= 1.7.5
Requires:      poco-json >= 1.7.5
Requires:      poco-net >= 1.7.5
Requires:      poco-netssl >= 1.7.5
Requires:      poco-util >= 1.7.5
Requires:      poco-xml >= 1.7.5
#Requires:      rpmlib(CompressedFileNames) <= 3.0.4-1
#Requires:      rpmlib(FileDigests) <= 4.6.0-1
#Requires:      rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Requires:      rtld(GNU_HASH)
Requires:      sed
Requires:      systemd
Requires:      xz-libs
Requires:      zlib
#Requires:      rpmlib(PayloadIsXz) <= 5.2-1
BuildRequires:  git
#suggest
#enhance
%description

%prep
cp %{SOURCE1} .
cp %{SOURCE2} .

%build
./autogen.sh
./configure --with-max-documents=10000 --with-max-connections=10000 --with-lokit-path=bundled/include --prefix= # the prefix is left intentional empty!

%install
%make_install
#cp %{SOURCE0} static.tar.gz
mkdir -p %{buildroot}/usr
mv %{buildroot}/share %{buildroot}/usr
mv %{buildroot}/bin %{buildroot}/usr
tar -zvxf static.tar.gz -C %{buildroot}
mkdir -p %{buildroot}/usr/share/loolwsd/loleaflet/dist/node_modules/jquery-ui/themes/ui-lightness/images
mv ui-bg_highlight-soft_100_eeeeee_1x100.png %{buildroot}/usr/share/loolwsd/loleaflet/dist/node_modules/jquery-ui/themes/ui-lightness/images/ui-bg_highlight-soft_100_eeeeee_1x100.png

%files
%config(noreplace) %attr(0644, root, root) "/etc/cron.d/loolwsd.cron"
%config %attr(0644, root, root) "/etc/loolwsd/loolkitconfig.xcu"
%config(noreplace) %attr(0640, lool, root) "/etc/loolwsd/loolwsd.xml"
%config(noreplace) %attr(0644, root, root) "/etc/sysconfig/loolwsd"
%attr(0755, root, root) "/usr/bin/loolconfig"
%attr(0755, root, root) "/usr/bin/loolforkit"
%attr(0755, root, root) "/usr/bin/loolmap"
%attr(0755, root, root) "/usr/bin/loolmount"
%attr(0755, root, root) "/usr/bin/loolstress"
%attr(0755, root, root) "/usr/bin/looltool"
%attr(0755, root, root) "/usr/bin/loolwsd"
%attr(0755, root, root) "/usr/bin/loolwsd-systemplate-setup"
%attr(0444, root, root) "/usr/lib/systemd/system/loolwsd.service"
%dir %attr(0755, root, root) "/usr/share/doc/loolwsd-2.1.3"
%doc %attr(0644, root, root) "/usr/share/doc/loolwsd-2.1.3/README"
%doc %attr(0644, root, root) "/usr/share/doc/loolwsd/README"
%doc %attr(0644, root, root) "/usr/share/doc/loolwsd/README.vars"
%doc %attr(0644, root, root) "/usr/share/doc/loolwsd/protocol.txt"
%doc %attr(0644, root, root) "/usr/share/doc/loolwsd/reference.txt"
%attr(0644, root, root) "/usr/share/loolwsd/discovery.xml"
%attr(0644, root, root) "/usr/share/loolwsd/favicon.ico"
%dir %attr(0755, root, root) "/usr/share/loolwsd/loleaflet"
%dir %attr(0755, root, root) "/usr/share/loolwsd/loleaflet/dist"
%dir %attr(0755, root, root) "/usr/share/loolwsd/loleaflet/dist/admin"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/admin-bundle.js"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/admin/admin-src.js"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/admin/admin.html"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/admin/adminAnalytics.html"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/admin/adminSettings.html"
%dir %attr(0755, root, root) "/usr/share/loolwsd/loleaflet/dist/admin/bootstrap"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/admin/bootstrap/LICENSE"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/admin/bootstrap/dashboard.css"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/admin/bootstrap/holder.min.js"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/admin/bootstrap/ie10-viewport-bug-workaround.css"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/admin/bootstrap/ie10-viewport-bug-workaround.js"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/admin/dashboard.css"
%dir %attr(0755, root, root) "/usr/share/loolwsd/loleaflet/dist/bootstrap"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/bootstrap/LICENSE"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/bootstrap/dashboard.css"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/bootstrap/holder.min.js"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/bootstrap/ie10-viewport-bug-workaround.js"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/bundle.js"
%dir %attr(0755, root, root) "/usr/share/loolwsd/loleaflet/dist/cursors"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/cursors/fill.cur"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/cursors/fill.png"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/errormessages.js"
%dir %attr(0755, root, root) "/usr/share/loolwsd/loleaflet/dist/images"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/README"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/handle_end.png"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/handle_start.png"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/layers-2x.png"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/layers.png"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc26049.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_accepttrackedchanges.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_alignblock.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_alignhorizontalcenter.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_alignleft.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_alignright.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_autosum.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_backcolor.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_backward.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_bold.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_cancel.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_checkbox.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_closedoc.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_color.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_currencyfield.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_datefield.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_decrementindent.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_decrementlevel.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_defaultbullet.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_defaultnumbering.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_deletepage.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_dia.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_downsearch.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_duplicatepage.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_editdoc.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_firstrecord.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_gallery.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_helpindex.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_insertpage.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_insertsymbol.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_inserttable.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_italic.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_lastrecord.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_nextrecord.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_numberformatdecdecimals.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_numberformatdecimal.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_numberformatincdecimals.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_numberformatpercent.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_ok.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_prevrecord.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_print.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_radiobutton.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_redo.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_rejecttrackedchange.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_save.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_saveas.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_showannotations.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_sortascending.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_sortdescending.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_strikeout.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_togglemergecells.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_underline.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_undo.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_upsearch.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_view100.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/lc_wraptext.svg"
%attr(0755, root, root) "/usr/share/loolwsd/loleaflet/dist/images/loading.gif"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/marker-icon-2x.png"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/marker-icon.png"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/marker-shadow.png"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/minus.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/plus.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/preview_placeholder.png"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/sc26049.png"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/submenu.svg"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/images/user.png"
%dir %attr(0755, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/admin-localizations.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-ab.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-af.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-am.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-an.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-anp.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-ar.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-as.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-ast.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-az.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-bar.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-be.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-bg.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-bm.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-bn.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-bn_IN.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-bo.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-br.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-brx.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-bs.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-ca-valencia.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-ca.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-ce.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-cs.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-cy.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-da.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-de.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-dgo.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-dz.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-el.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-en_AU.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-en_GB.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-en_ZA.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-eo.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-es.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-et.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-eu.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-fa.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-fi.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-fr.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-fur.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-fy.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-ga.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-gbm.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-gd.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-gl.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-gu.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-gug.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-he.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-hi.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-hr.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-hu.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-hy.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-id.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-is.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-it.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-ja.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-jv.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-ka.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-kab.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-kk.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-kl.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-km.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-kmr-Latn.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-kn.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-ko.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-kok.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-ks.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-ky.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-lb.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-lo.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-localizations.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-lt.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-lv.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-mai.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-mk.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-ml.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-mn.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-mni.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-mr.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-mt.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-my.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-nah.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-nb.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-ne.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-nl.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-nn.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-nqo.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-nr.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-nso.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-oc.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-om.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-or.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-pa_IN.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-pap_CW.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-pl.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-pt.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-pt_BR.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-ro.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-ru.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-rw.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-sa_IN.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-sah.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-sat.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-sd.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-si.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-sid.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-sk.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-sl.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-sq.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-ss.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-st.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-sv.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-sw_TZ.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-ta.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-te.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-tg.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-th.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-ti.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-tn.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-tr.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-ts.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-tt.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-ug.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-uk.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-ur.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-uz.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-ve.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-vec.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-vi.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-wo.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-xh.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-zh_CN.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-zh_TW.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/help-zu.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/localizations.json"
%dir %attr(0755, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles-localizations.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/ab.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/af.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/am.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/an.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/ar.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/as.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/ast.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/be.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/bg.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/bn-IN.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/bn.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/bo.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/br.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/brx.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/bs.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/ca-valencia.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/ca.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/cs.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/cy.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/da.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/de.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/dgo.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/dz.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/el.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/en-GB.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/en-ZA.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/eo.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/es.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/et.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/eu.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/fa.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/fi.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/fr.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/ga.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/gd.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/gl.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/gu.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/gug.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/he.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/hi.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/hr.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/hu.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/id.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/is.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/it.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/ja.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/ka.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/kk.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/kl.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/km.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/kmr-Latn.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/kn.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/ko.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/kok.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/ks.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/ky.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/lb.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/lo.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/lt.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/lv.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/mai.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/mk.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/ml.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/mn.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/mni.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/mr.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/my.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/nb.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/ne.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/nl.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/nn.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/nr.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/nso.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/oc.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/om.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/or.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/pa-IN.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/pl.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/pt-BR.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/pt.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/ro.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/ru.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/rw.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/sa-IN.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/sat.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/sd.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/si.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/sid.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/sk.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/sl.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/sq.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/sr-Latn.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/sr.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/ss.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/st.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/sv.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/sw-TZ.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/ta.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/te.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/tg.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/th.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/ti.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/tn.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/tr.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/ts.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/tt.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/ug.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/uk.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/ur.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/uz.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/ve.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/vi.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/xh.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/zh-CN.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/zh-TW.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/styles/zu.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-ab.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-af.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-am.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-an.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-anp.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-ar.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-as.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-ast.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-az.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-bar.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-be.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-bg.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-bm.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-bn.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-bn_IN.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-bo.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-br.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-brx.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-bs.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-ca-valencia.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-ca.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-ce.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-cs.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-cy.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-da.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-de.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-dgo.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-dz.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-el.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-en_AU.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-en_GB.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-en_ZA.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-eo.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-es.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-et.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-eu.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-fa.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-fi.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-fr.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-fur.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-fy.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-ga.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-gbm.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-gd.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-gl.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-gu.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-gug.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-he.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-hi.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-hr.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-hu.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-hy.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-id.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-is.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-it.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-ja.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-jv.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-ka.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-kab.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-kk.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-kl.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-km.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-kmr-Latn.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-kn.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-ko.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-kok.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-ks.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-ky.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-lb.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-lo.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-lt.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-lv.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-mai.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-mk.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-ml.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-mn.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-mni.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-mr.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-mt.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-my.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-nah.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-nb.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-ne.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-nl.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-nn.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-nqo.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-nr.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-nso.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-oc.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-om.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-or.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-pa_IN.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-pap_CW.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-pl.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-pt.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-pt_BR.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-ro.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-ru.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-rw.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-sa_IN.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-sah.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-sat.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-sd.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-si.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-sid.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-sk.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-sl.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-sq.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-ss.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-st.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-sv.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-sw_TZ.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-ta.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-te.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-tg.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-th.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-ti.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-tn.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-tr.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-ts.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-tt.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-ug.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-uk.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-ur.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-uz.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-ve.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-vec.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-vi.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-wo.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-xh.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-zh_CN.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-zh_TW.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/ui-zu.json"
%dir %attr(0755, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno-localizations.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/ab.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/af.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/am.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/an.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/ar.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/as.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/ast.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/az.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/be.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/bg.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/bn-IN.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/bn.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/bo.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/br.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/brx.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/bs.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/ca-valencia.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/ca.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/cs.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/cy.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/da.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/de.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/dgo.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/dz.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/el.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/en-GB.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/en-ZA.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/eo.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/es.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/et.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/eu.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/fa.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/fi.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/fr.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/ga.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/gd.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/gl.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/gu.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/gug.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/he.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/hi.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/hr.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/hu.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/id.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/is.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/it.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/ja.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/jv.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/ka.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/kk.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/kl.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/km.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/kmr-Latn.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/kn.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/ko.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/kok.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/ks.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/ky.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/lb.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/lo.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/lt.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/lv.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/mai.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/mk.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/ml.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/mn.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/mni.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/mr.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/my.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/nb.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/ne.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/nl.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/nn.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/nr.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/nso.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/oc.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/om.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/or.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/pa-IN.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/pl.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/pt-BR.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/pt.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/ro.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/ru.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/rw.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/sa-IN.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/sah.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/sat.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/sd.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/si.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/sid.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/sk.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/sl.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/sq.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/sr-Latn.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/sr.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/ss.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/st.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/sv.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/sw-TZ.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/ta.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/te.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/tg.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/th.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/ti.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/tn.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/tr.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/ts.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/tt.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/ug.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/uk.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/ur.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/uz.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/ve.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/vi.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/xh.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/zh-CN.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/zh-TW.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/l10n/uno/zu.json"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/leaflet-src.js"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/leaflet.css"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/leaflet.js"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/loading.html"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/loleaflet-help.html"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/loleaflet.css"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/loleaflet.html"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/menubar.css"
%dir %attr(0755, root, root) "/usr/share/loolwsd/loleaflet/dist/node_modules"
%dir %attr(0755, root, root) "/usr/share/loolwsd/loleaflet/dist/node_modules/jquery-ui"
%dir %attr(0755, root, root) "/usr/share/loolwsd/loleaflet/dist/node_modules/jquery-ui/themes"
%dir %attr(0755, root, root) "/usr/share/loolwsd/loleaflet/dist/node_modules/jquery-ui/themes/ui-lightness"
%dir %attr(0755, root, root) "/usr/share/loolwsd/loleaflet/dist/node_modules/jquery-ui/themes/ui-lightness/images"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/node_modules/jquery-ui/themes/ui-lightness/images/ui-bg_highlight-soft_100_eeeeee_1x100.png"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/partsPreviewControl.css"
%dir %attr(0755, root, root) "/usr/share/loolwsd/loleaflet/dist/plugins"
%dir %attr(0755, root, root) "/usr/share/loolwsd/loleaflet/dist/plugins/draw-0.2.4"
%dir %attr(0755, root, root) "/usr/share/loolwsd/loleaflet/dist/plugins/draw-0.2.4/dist"
%dir %attr(0755, root, root) "/usr/share/loolwsd/loleaflet/dist/plugins/draw-0.2.4/dist/images"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/plugins/draw-0.2.4/dist/images/spritesheet-2x.png"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/plugins/draw-0.2.4/dist/images/spritesheet.png"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/plugins/draw-0.2.4/dist/leaflet.draw-src.js"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/plugins/draw-0.2.4/dist/leaflet.draw.css"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/plugins/draw-0.2.4/dist/leaflet.draw.js"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/scrollBar.css"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/searchControl.css"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/selectionMarkers.css"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/spreadsheet.css"
%dir %attr(0755, root, root) "/usr/share/loolwsd/loleaflet/dist/toolbar"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/toolbar.css"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/toolbar/toolbar.js"
%attr(0644, root, root) "/usr/share/loolwsd/loleaflet/dist/toolbar/w2ui.min.js"
%attr(0644, root, root) "/usr/share/loolwsd/robots.txt"
%pre -p /bin/sh

getent group lool >/dev/null || groupadd -r lool
getent passwd lool >/dev/null || useradd -g lool -r lool
%post -p /bin/sh
setcap cap_fowner,cap_mknod,cap_sys_chroot=ep /usr/bin/loolforkit
setcap cap_sys_admin=ep /usr/bin/loolmount

mkdir -p /var/cache/loolwsd && chown lool:lool /var/cache/loolwsd
rm -rf /var/cache/loolwsd/*

# Figure out where LO is installed, let's hope it is not a mount point
# Create a directory for loolwsd on the same file system
loroot=/opt/collaboraoffice5.3
loolparent=`cd ${loroot} && cd .. && /bin/pwd`

rm -rf ${loolparent}/lool
mkdir -p ${loolparent}/lool/child-roots
chown lool:lool ${loolparent}/lool
chown lool:lool ${loolparent}/lool/child-roots

fc-cache ${loroot}/share/fonts/truetype
su lool -c "loolwsd-systemplate-setup ${loolparent}/lool/systemplate ${loroot} >/dev/null 2>&1"


if [ $1 -eq 1 ] ; then
        # Initial installation
        systemctl preset loolwsd.service >/dev/null 2>&1 || :
fi
%preun -p /bin/sh

if [ $1 -eq 0 ] ; then
        # Package removal, not upgrade
        systemctl --no-reload disable loolwsd.service > /dev/null 2>&1 || :
        systemctl stop loolwsd.service > /dev/null 2>&1 || :
fi
%postun -p /bin/sh

systemctl daemon-reload >/dev/null 2>&1 || :
%changelog
* Mon Aug 03 2015 Mihai Varga
- added the cronjob

* Tue May 19 2015 Tor Lillqvist
- Initial RPM release
